log enable -f /azerothcore/env/dist/logs/lldb_log.txt lldb commands process
target create /azerothcore/env/dist/bin/worldserver
settings set target.process.python-os-plugin-path ""

run

thread backtrace all
frame variable
process status
